name: PR

on: pull_request

jobs:
  build:
    name: Eslint and Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: yarn
      - name: Run tests
        run: yarn jest